// <auto-generated />
using System;
using ENSPRONET.Services.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ENSPRONET.Services.Migrations
{
    [DbContext(typeof(ENSPRONETContext))]
    [Migration("20220209171353_addednavigationpropweatherforecast")]
    partial class addednavigationpropweatherforecast
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("ENSPRONET.Domains.Domains.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternetDomain")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumericCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubDivisionCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alpha2Code = "GF",
                            Alpha3Code = "GUF",
                            CountryName = "French Guiana",
                            InternetDomain = ".gf",
                            NumericCode = 254,
                            SubDivisionCode = "FG"
                        },
                        new
                        {
                            Id = 2,
                            Alpha2Code = "TG",
                            Alpha3Code = "TGO",
                            CountryName = "Togo",
                            InternetDomain = ".tg",
                            NumericCode = 768,
                            SubDivisionCode = "TO"
                        },
                        new
                        {
                            Id = 3,
                            Alpha2Code = "OM",
                            Alpha3Code = "OMN",
                            CountryName = "Oman",
                            InternetDomain = ".om",
                            NumericCode = 512,
                            SubDivisionCode = "MU"
                        },
                        new
                        {
                            Id = 4,
                            Alpha2Code = "SO",
                            Alpha3Code = "SOM",
                            CountryName = "Somalia",
                            InternetDomain = ".so",
                            NumericCode = 706,
                            SubDivisionCode = "SO"
                        },
                        new
                        {
                            Id = 5,
                            Alpha2Code = "NL",
                            Alpha3Code = "NLD",
                            CountryName = "Netherlands",
                            InternetDomain = ".nl",
                            NumericCode = 528,
                            SubDivisionCode = "NL"
                        },
                        new
                        {
                            Id = 6,
                            Alpha2Code = "KM",
                            Alpha3Code = "COM",
                            CountryName = "Comoros",
                            InternetDomain = ".km",
                            NumericCode = 174,
                            SubDivisionCode = "CN"
                        },
                        new
                        {
                            Id = 7,
                            Alpha2Code = "KR",
                            Alpha3Code = "KOR",
                            CountryName = "South Korea",
                            InternetDomain = ".kr",
                            NumericCode = 410,
                            SubDivisionCode = "KS"
                        },
                        new
                        {
                            Id = 8,
                            Alpha2Code = "GA",
                            Alpha3Code = "GAB",
                            CountryName = "Gabon",
                            InternetDomain = ".ga",
                            NumericCode = 266,
                            SubDivisionCode = "GB"
                        },
                        new
                        {
                            Id = 9,
                            Alpha2Code = "BJ",
                            Alpha3Code = "BEN",
                            CountryName = "Benin",
                            InternetDomain = ".bj",
                            NumericCode = 204,
                            SubDivisionCode = "BN"
                        },
                        new
                        {
                            Id = 10,
                            Alpha2Code = "FR",
                            Alpha3Code = "FRA",
                            CountryName = "France",
                            InternetDomain = ".fr",
                            NumericCode = 250,
                            SubDivisionCode = "FR"
                        },
                        new
                        {
                            Id = 11,
                            Alpha2Code = "PA",
                            Alpha3Code = "PAN",
                            CountryName = "Panama",
                            InternetDomain = ".pa",
                            NumericCode = 591,
                            SubDivisionCode = "PM"
                        },
                        new
                        {
                            Id = 12,
                            Alpha2Code = "BW",
                            Alpha3Code = "BWA",
                            CountryName = "Botswana",
                            InternetDomain = ".bw",
                            NumericCode = 72,
                            SubDivisionCode = "BC"
                        },
                        new
                        {
                            Id = 13,
                            Alpha2Code = "MP",
                            Alpha3Code = "MNP",
                            CountryName = "Northern Mariana Islands",
                            InternetDomain = ".mp",
                            NumericCode = 580,
                            SubDivisionCode = "CQ"
                        },
                        new
                        {
                            Id = 14,
                            Alpha2Code = "KP",
                            Alpha3Code = "PRK",
                            CountryName = "North Korea",
                            InternetDomain = ".kp",
                            NumericCode = 408,
                            SubDivisionCode = "KN"
                        },
                        new
                        {
                            Id = 15,
                            Alpha2Code = "FJ",
                            Alpha3Code = "FJI",
                            CountryName = "Fiji",
                            InternetDomain = ".fj",
                            NumericCode = 242,
                            SubDivisionCode = "FJ"
                        },
                        new
                        {
                            Id = 16,
                            Alpha2Code = "FR",
                            Alpha3Code = "FRA",
                            CountryName = "France",
                            InternetDomain = ".fr",
                            NumericCode = 250,
                            SubDivisionCode = "FR"
                        },
                        new
                        {
                            Id = 17,
                            Alpha2Code = "NE",
                            Alpha3Code = "NER",
                            CountryName = "Niger",
                            InternetDomain = ".ne",
                            NumericCode = 562,
                            SubDivisionCode = "NG"
                        },
                        new
                        {
                            Id = 18,
                            Alpha2Code = "BE",
                            Alpha3Code = "BEL",
                            CountryName = "Belgium",
                            InternetDomain = ".be",
                            NumericCode = 56,
                            SubDivisionCode = "BE"
                        },
                        new
                        {
                            Id = 19,
                            Alpha2Code = "CX",
                            Alpha3Code = "CXR",
                            CountryName = "Christmas Island",
                            InternetDomain = ".cx",
                            NumericCode = 162,
                            SubDivisionCode = "KT"
                        },
                        new
                        {
                            Id = 20,
                            Alpha2Code = "BD",
                            Alpha3Code = "BGD",
                            CountryName = "Bangladesh",
                            InternetDomain = ".bd",
                            NumericCode = 50,
                            SubDivisionCode = "BG"
                        },
                        new
                        {
                            Id = 21,
                            Alpha2Code = "BZ",
                            Alpha3Code = "BLZ",
                            CountryName = "Belize",
                            InternetDomain = ".bz",
                            NumericCode = 84,
                            SubDivisionCode = "BH"
                        },
                        new
                        {
                            Id = 22,
                            Alpha2Code = "CU",
                            Alpha3Code = "CUB",
                            CountryName = "Cuba",
                            InternetDomain = ".cu",
                            NumericCode = 192,
                            SubDivisionCode = "CU"
                        },
                        new
                        {
                            Id = 23,
                            Alpha2Code = "AQ",
                            Alpha3Code = "ATA",
                            CountryName = "Antarctica",
                            InternetDomain = ".aq",
                            NumericCode = 10,
                            SubDivisionCode = "AY"
                        },
                        new
                        {
                            Id = 24,
                            Alpha2Code = "KP",
                            Alpha3Code = "PRK",
                            CountryName = "North Korea",
                            InternetDomain = ".kp",
                            NumericCode = 408,
                            SubDivisionCode = "KN"
                        },
                        new
                        {
                            Id = 25,
                            Alpha2Code = "ZW",
                            Alpha3Code = "ZWE",
                            CountryName = "Zimbabwe",
                            InternetDomain = ".zw",
                            NumericCode = 716,
                            SubDivisionCode = "ZI"
                        },
                        new
                        {
                            Id = 26,
                            Alpha2Code = "DZ",
                            Alpha3Code = "DZA",
                            CountryName = "Algeria",
                            InternetDomain = ".dz",
                            NumericCode = 12,
                            SubDivisionCode = "AG"
                        },
                        new
                        {
                            Id = 27,
                            Alpha2Code = "PK",
                            Alpha3Code = "PAK",
                            CountryName = "Pakistan",
                            InternetDomain = ".pk",
                            NumericCode = 586,
                            SubDivisionCode = "PK"
                        },
                        new
                        {
                            Id = 28,
                            Alpha2Code = "DJ",
                            Alpha3Code = "DJI",
                            CountryName = "Djibouti",
                            InternetDomain = ".dj",
                            NumericCode = 262,
                            SubDivisionCode = "DJ"
                        },
                        new
                        {
                            Id = 29,
                            Alpha2Code = "BB",
                            Alpha3Code = "BRB",
                            CountryName = "Barbados",
                            InternetDomain = ".bb",
                            NumericCode = 52,
                            SubDivisionCode = "BB"
                        },
                        new
                        {
                            Id = 30,
                            Alpha2Code = "AS",
                            Alpha3Code = "ASM",
                            CountryName = "American Samoa",
                            InternetDomain = ".as",
                            NumericCode = 16,
                            SubDivisionCode = "AQ"
                        },
                        new
                        {
                            Id = 31,
                            Alpha2Code = "MG",
                            Alpha3Code = "MDG",
                            CountryName = "Madagascar",
                            InternetDomain = ".mg",
                            NumericCode = 450,
                            SubDivisionCode = "MA"
                        },
                        new
                        {
                            Id = 32,
                            Alpha2Code = "VA",
                            Alpha3Code = "VAT",
                            CountryName = "Vatican",
                            InternetDomain = ".va",
                            NumericCode = 336,
                            SubDivisionCode = "VT"
                        },
                        new
                        {
                            Id = 33,
                            Alpha2Code = "VE",
                            Alpha3Code = "VEN",
                            CountryName = "Venezuela",
                            InternetDomain = ".ve",
                            NumericCode = 862,
                            SubDivisionCode = "VE"
                        },
                        new
                        {
                            Id = 34,
                            Alpha2Code = "AM",
                            Alpha3Code = "ARM",
                            CountryName = "Armenia",
                            InternetDomain = ".am",
                            NumericCode = 51,
                            SubDivisionCode = "AM"
                        },
                        new
                        {
                            Id = 35,
                            Alpha2Code = "FR",
                            Alpha3Code = "FRA",
                            CountryName = "France",
                            InternetDomain = ".fr",
                            NumericCode = 250,
                            SubDivisionCode = "FR"
                        },
                        new
                        {
                            Id = 36,
                            Alpha2Code = "CG",
                            Alpha3Code = "COG",
                            CountryName = "Republic of the Congo",
                            InternetDomain = ".cg",
                            NumericCode = 178,
                            SubDivisionCode = "CF"
                        },
                        new
                        {
                            Id = 37,
                            Alpha2Code = "IE",
                            Alpha3Code = "IRL",
                            CountryName = "Ireland",
                            InternetDomain = ".ie",
                            NumericCode = 372,
                            SubDivisionCode = "EI"
                        },
                        new
                        {
                            Id = 38,
                            Alpha2Code = "AT",
                            Alpha3Code = "AUT",
                            CountryName = "Austria",
                            InternetDomain = ".at",
                            NumericCode = 40,
                            SubDivisionCode = "AU"
                        },
                        new
                        {
                            Id = 39,
                            Alpha2Code = "BL",
                            Alpha3Code = "BLM",
                            CountryName = "Saint Barthelemy",
                            InternetDomain = ".gp",
                            NumericCode = 652,
                            SubDivisionCode = "TB"
                        },
                        new
                        {
                            Id = 40,
                            Alpha2Code = "LR",
                            Alpha3Code = "LBR",
                            CountryName = "Liberia",
                            InternetDomain = ".lr",
                            NumericCode = 430,
                            SubDivisionCode = "LI"
                        },
                        new
                        {
                            Id = 41,
                            Alpha2Code = "DK",
                            Alpha3Code = "DNK",
                            CountryName = "Denmark",
                            InternetDomain = ".dk",
                            NumericCode = 208,
                            SubDivisionCode = "DA"
                        },
                        new
                        {
                            Id = 42,
                            Alpha2Code = "RU",
                            Alpha3Code = "RUS",
                            CountryName = "Russia",
                            InternetDomain = ".ru",
                            NumericCode = 643,
                            SubDivisionCode = "RS"
                        },
                        new
                        {
                            Id = 43,
                            Alpha2Code = "BJ",
                            Alpha3Code = "BEN",
                            CountryName = "Benin",
                            InternetDomain = ".bj",
                            NumericCode = 204,
                            SubDivisionCode = "BN"
                        },
                        new
                        {
                            Id = 44,
                            Alpha2Code = "MH",
                            Alpha3Code = "MHL",
                            CountryName = "Marshall Islands",
                            InternetDomain = ".mh",
                            NumericCode = 584,
                            SubDivisionCode = "RM"
                        },
                        new
                        {
                            Id = 45,
                            Alpha2Code = "NC",
                            Alpha3Code = "NCL",
                            CountryName = "New Caledonia",
                            InternetDomain = ".nc",
                            NumericCode = 540,
                            SubDivisionCode = "NC"
                        },
                        new
                        {
                            Id = 46,
                            Alpha2Code = "MD",
                            Alpha3Code = "MDA",
                            CountryName = "Moldova",
                            InternetDomain = ".md",
                            NumericCode = 498,
                            SubDivisionCode = "MD"
                        },
                        new
                        {
                            Id = 47,
                            Alpha2Code = "AF",
                            Alpha3Code = "AFG",
                            CountryName = "Afghanistan",
                            InternetDomain = ".af",
                            NumericCode = 4,
                            SubDivisionCode = "AF"
                        },
                        new
                        {
                            Id = 48,
                            Alpha2Code = "PH",
                            Alpha3Code = "PHL",
                            CountryName = "Philippines",
                            InternetDomain = ".ph",
                            NumericCode = 608,
                            SubDivisionCode = "RP"
                        },
                        new
                        {
                            Id = 49,
                            Alpha2Code = "MX",
                            Alpha3Code = "MEX",
                            CountryName = "Mexico",
                            InternetDomain = ".mx",
                            NumericCode = 484,
                            SubDivisionCode = "MX"
                        },
                        new
                        {
                            Id = 50,
                            Alpha2Code = "MO",
                            Alpha3Code = "MAC",
                            CountryName = "Macao",
                            InternetDomain = ".mo",
                            NumericCode = 446,
                            SubDivisionCode = "MC"
                        },
                        new
                        {
                            Id = 51,
                            Alpha2Code = "PN",
                            Alpha3Code = "PCN",
                            CountryName = "Pitcairn",
                            InternetDomain = ".pn",
                            NumericCode = 612,
                            SubDivisionCode = "PC"
                        },
                        new
                        {
                            Id = 52,
                            Alpha2Code = "ZA",
                            Alpha3Code = "ZAF",
                            CountryName = "South Africa",
                            InternetDomain = ".za",
                            NumericCode = 710,
                            SubDivisionCode = "SF"
                        },
                        new
                        {
                            Id = 53,
                            Alpha2Code = "AL",
                            Alpha3Code = "ALB",
                            CountryName = "Albania",
                            InternetDomain = ".al",
                            NumericCode = 8,
                            SubDivisionCode = "AL"
                        },
                        new
                        {
                            Id = 54,
                            Alpha2Code = "YT",
                            Alpha3Code = "MYT",
                            CountryName = "Mayotte",
                            InternetDomain = ".yt",
                            NumericCode = 175,
                            SubDivisionCode = "MF"
                        },
                        new
                        {
                            Id = 55,
                            Alpha2Code = "CH",
                            Alpha3Code = "CHE",
                            CountryName = "Switzerland",
                            InternetDomain = ".ch",
                            NumericCode = 756,
                            SubDivisionCode = "SZ"
                        },
                        new
                        {
                            Id = 56,
                            Alpha2Code = "RS",
                            Alpha3Code = "SRB",
                            CountryName = "Serbia",
                            InternetDomain = ".rs",
                            NumericCode = 688,
                            SubDivisionCode = "RI"
                        },
                        new
                        {
                            Id = 57,
                            Alpha2Code = "UZ",
                            Alpha3Code = "UZB",
                            CountryName = "Uzbekistan",
                            InternetDomain = ".uz",
                            NumericCode = 860,
                            SubDivisionCode = "UZ"
                        },
                        new
                        {
                            Id = 58,
                            Alpha2Code = "GY",
                            Alpha3Code = "GUY",
                            CountryName = "Guyana",
                            InternetDomain = ".gy",
                            NumericCode = 328,
                            SubDivisionCode = "GY"
                        },
                        new
                        {
                            Id = 59,
                            Alpha2Code = "BM",
                            Alpha3Code = "BMU",
                            CountryName = "Bermuda",
                            InternetDomain = ".bm",
                            NumericCode = 60,
                            SubDivisionCode = "BD"
                        },
                        new
                        {
                            Id = 60,
                            Alpha2Code = "CC",
                            Alpha3Code = "CCK",
                            CountryName = "Cocos Islands",
                            InternetDomain = ".cc",
                            NumericCode = 166,
                            SubDivisionCode = "CK"
                        },
                        new
                        {
                            Id = 61,
                            Alpha2Code = "LB",
                            Alpha3Code = "LBN",
                            CountryName = "Lebanon",
                            InternetDomain = ".lb",
                            NumericCode = 422,
                            SubDivisionCode = "LE"
                        },
                        new
                        {
                            Id = 62,
                            Alpha2Code = "CR",
                            Alpha3Code = "CRI",
                            CountryName = "Costa Rica",
                            InternetDomain = ".cr",
                            NumericCode = 188,
                            SubDivisionCode = "CS"
                        },
                        new
                        {
                            Id = 63,
                            Alpha2Code = "CX",
                            Alpha3Code = "CXR",
                            CountryName = "Christmas Island",
                            InternetDomain = ".cx",
                            NumericCode = 162,
                            SubDivisionCode = "KT"
                        },
                        new
                        {
                            Id = 64,
                            Alpha2Code = "AR",
                            Alpha3Code = "ARG",
                            CountryName = "Argentina",
                            InternetDomain = ".ar",
                            NumericCode = 32,
                            SubDivisionCode = "AR"
                        },
                        new
                        {
                            Id = 65,
                            Alpha2Code = "LU",
                            Alpha3Code = "LUX",
                            CountryName = "Luxembourg",
                            InternetDomain = ".lu",
                            NumericCode = 442,
                            SubDivisionCode = "LU"
                        },
                        new
                        {
                            Id = 66,
                            Alpha2Code = "KY",
                            Alpha3Code = "CYM",
                            CountryName = "Cayman Islands",
                            InternetDomain = ".ky",
                            NumericCode = 136,
                            SubDivisionCode = "CJ"
                        },
                        new
                        {
                            Id = 67,
                            Alpha2Code = "HM",
                            Alpha3Code = "HMD",
                            CountryName = "Heard Island and McDonald Islands",
                            InternetDomain = ".hm",
                            NumericCode = 334,
                            SubDivisionCode = "HM"
                        },
                        new
                        {
                            Id = 68,
                            Alpha2Code = "DO",
                            Alpha3Code = "DOM",
                            CountryName = "Dominican Republic",
                            InternetDomain = ".do",
                            NumericCode = 214,
                            SubDivisionCode = "DR"
                        },
                        new
                        {
                            Id = 69,
                            Alpha2Code = "GL",
                            Alpha3Code = "GRL",
                            CountryName = "Greenland",
                            InternetDomain = ".gl",
                            NumericCode = 304,
                            SubDivisionCode = "GL"
                        },
                        new
                        {
                            Id = 70,
                            Alpha2Code = "NZ",
                            Alpha3Code = "NZL",
                            CountryName = "New Zealand",
                            InternetDomain = ".nz",
                            NumericCode = 554,
                            SubDivisionCode = "NZ"
                        },
                        new
                        {
                            Id = 71,
                            Alpha2Code = "TR",
                            Alpha3Code = "TUR",
                            CountryName = "Turkey",
                            InternetDomain = ".tr",
                            NumericCode = 792,
                            SubDivisionCode = "TU"
                        },
                        new
                        {
                            Id = 72,
                            Alpha2Code = "CD",
                            Alpha3Code = "COD",
                            CountryName = "Democratic Republic of the Congo",
                            InternetDomain = ".cd",
                            NumericCode = 180,
                            SubDivisionCode = "CG"
                        },
                        new
                        {
                            Id = 73,
                            Alpha2Code = "ZM",
                            Alpha3Code = "ZMB",
                            CountryName = "Zambia",
                            InternetDomain = ".zm",
                            NumericCode = 894,
                            SubDivisionCode = "ZA"
                        },
                        new
                        {
                            Id = 74,
                            Alpha2Code = "LT",
                            Alpha3Code = "LTU",
                            CountryName = "Lithuania",
                            InternetDomain = ".lt",
                            NumericCode = 440,
                            SubDivisionCode = "LH"
                        },
                        new
                        {
                            Id = 75,
                            Alpha2Code = "CU",
                            Alpha3Code = "CUB",
                            CountryName = "Cuba",
                            InternetDomain = ".cu",
                            NumericCode = 192,
                            SubDivisionCode = "CU"
                        },
                        new
                        {
                            Id = 76,
                            Alpha2Code = "LA",
                            Alpha3Code = "LAO",
                            CountryName = "Laos",
                            InternetDomain = ".la",
                            NumericCode = 418,
                            SubDivisionCode = "LA"
                        },
                        new
                        {
                            Id = 77,
                            Alpha2Code = "VE",
                            Alpha3Code = "VEN",
                            CountryName = "Venezuela",
                            InternetDomain = ".ve",
                            NumericCode = 862,
                            SubDivisionCode = "VE"
                        },
                        new
                        {
                            Id = 78,
                            Alpha2Code = "IS",
                            Alpha3Code = "ISL",
                            CountryName = "Iceland",
                            InternetDomain = ".is",
                            NumericCode = 352,
                            SubDivisionCode = "IC"
                        },
                        new
                        {
                            Id = 79,
                            Alpha2Code = "AI",
                            Alpha3Code = "AIA",
                            CountryName = "Anguilla",
                            InternetDomain = ".ai",
                            NumericCode = 660,
                            SubDivisionCode = "AV"
                        },
                        new
                        {
                            Id = 80,
                            Alpha2Code = "BE",
                            Alpha3Code = "BEL",
                            CountryName = "Belgium",
                            InternetDomain = ".be",
                            NumericCode = 56,
                            SubDivisionCode = "BE"
                        },
                        new
                        {
                            Id = 81,
                            Alpha2Code = "TD",
                            Alpha3Code = "TCD",
                            CountryName = "Chad",
                            InternetDomain = ".td",
                            NumericCode = 148,
                            SubDivisionCode = "CD"
                        },
                        new
                        {
                            Id = 82,
                            Alpha2Code = "AN",
                            Alpha3Code = "ANT",
                            CountryName = "Netherlands Antilles",
                            InternetDomain = ".an",
                            NumericCode = 530,
                            SubDivisionCode = "NT"
                        },
                        new
                        {
                            Id = 83,
                            Alpha2Code = "LY",
                            Alpha3Code = "LBY",
                            CountryName = "Libya",
                            InternetDomain = ".ly",
                            NumericCode = 434,
                            SubDivisionCode = "LY"
                        },
                        new
                        {
                            Id = 84,
                            Alpha2Code = "MS",
                            Alpha3Code = "MSR",
                            CountryName = "Montserrat",
                            InternetDomain = ".ms",
                            NumericCode = 500,
                            SubDivisionCode = "MH"
                        },
                        new
                        {
                            Id = 85,
                            Alpha2Code = "AM",
                            Alpha3Code = "ARM",
                            CountryName = "Armenia",
                            InternetDomain = ".am",
                            NumericCode = 51,
                            SubDivisionCode = "AM"
                        },
                        new
                        {
                            Id = 86,
                            Alpha2Code = "TF",
                            Alpha3Code = "ATF",
                            CountryName = "French Southern Territories",
                            InternetDomain = ".tf",
                            NumericCode = 260,
                            SubDivisionCode = "FS"
                        },
                        new
                        {
                            Id = 87,
                            Alpha2Code = "LA",
                            Alpha3Code = "LAO",
                            CountryName = "Laos",
                            InternetDomain = ".la",
                            NumericCode = 418,
                            SubDivisionCode = "LA"
                        },
                        new
                        {
                            Id = 88,
                            Alpha2Code = "KN",
                            Alpha3Code = "KNA",
                            CountryName = "Saint Kitts and Nevis",
                            InternetDomain = ".kn",
                            NumericCode = 659,
                            SubDivisionCode = "SC"
                        },
                        new
                        {
                            Id = 89,
                            Alpha2Code = "AT",
                            Alpha3Code = "AUT",
                            CountryName = "Austria",
                            InternetDomain = ".at",
                            NumericCode = 40,
                            SubDivisionCode = "AU"
                        },
                        new
                        {
                            Id = 90,
                            Alpha2Code = "NR",
                            Alpha3Code = "NRU",
                            CountryName = "Nauru",
                            InternetDomain = ".nr",
                            NumericCode = 520,
                            SubDivisionCode = "NR"
                        },
                        new
                        {
                            Id = 91,
                            Alpha2Code = "VN",
                            Alpha3Code = "VNM",
                            CountryName = "Vietnam",
                            InternetDomain = ".vn",
                            NumericCode = 704,
                            SubDivisionCode = "VM"
                        },
                        new
                        {
                            Id = 92,
                            Alpha2Code = "MO",
                            Alpha3Code = "MAC",
                            CountryName = "Macao",
                            InternetDomain = ".mo",
                            NumericCode = 446,
                            SubDivisionCode = "MC"
                        },
                        new
                        {
                            Id = 93,
                            Alpha2Code = "BD",
                            Alpha3Code = "BGD",
                            CountryName = "Bangladesh",
                            InternetDomain = ".bd",
                            NumericCode = 50,
                            SubDivisionCode = "BG"
                        },
                        new
                        {
                            Id = 94,
                            Alpha2Code = "VA",
                            Alpha3Code = "VAT",
                            CountryName = "Vatican",
                            InternetDomain = ".va",
                            NumericCode = 336,
                            SubDivisionCode = "VT"
                        },
                        new
                        {
                            Id = 95,
                            Alpha2Code = "AU",
                            Alpha3Code = "AUS",
                            CountryName = "Australia",
                            InternetDomain = ".au",
                            NumericCode = 36,
                            SubDivisionCode = "AS"
                        },
                        new
                        {
                            Id = 96,
                            Alpha2Code = "OM",
                            Alpha3Code = "OMN",
                            CountryName = "Oman",
                            InternetDomain = ".om",
                            NumericCode = 512,
                            SubDivisionCode = "MU"
                        },
                        new
                        {
                            Id = 97,
                            Alpha2Code = "CU",
                            Alpha3Code = "CUB",
                            CountryName = "Cuba",
                            InternetDomain = ".cu",
                            NumericCode = 192,
                            SubDivisionCode = "CU"
                        },
                        new
                        {
                            Id = 98,
                            Alpha2Code = "CX",
                            Alpha3Code = "CXR",
                            CountryName = "Christmas Island",
                            InternetDomain = ".cx",
                            NumericCode = 162,
                            SubDivisionCode = "KT"
                        },
                        new
                        {
                            Id = 99,
                            Alpha2Code = "SO",
                            Alpha3Code = "SOM",
                            CountryName = "Somalia",
                            InternetDomain = ".so",
                            NumericCode = 706,
                            SubDivisionCode = "SO"
                        },
                        new
                        {
                            Id = 100,
                            Alpha2Code = "TJ",
                            Alpha3Code = "TJK",
                            CountryName = "Tajikistan",
                            InternetDomain = ".tj",
                            NumericCode = 762,
                            SubDivisionCode = "TI"
                        });
                });

            modelBuilder.Entity("ENSPRONET.Domains.Domains.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemperatureF")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("WeatherForecast");
                });

            modelBuilder.Entity("ENSPRONET.Domains.Domains.WeatherForecast", b =>
                {
                    b.HasOne("ENSPRONET.Domains.Domains.Country", "Country")
                        .WithMany("WeatherForecasts")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ENSPRONET.Domains.Domains.Country", b =>
                {
                    b.Navigation("WeatherForecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
