// <auto-generated />
using System;
using ENSPRONET.Services.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ENSPRONET.Services.Migrations
{
    [DbContext(typeof(ENSPRONETContext))]
    [Migration("20220209170023_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("ENSPRONET.Domains.Domains.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternetDomain")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumericCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubDivisionCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alpha2Code = "GU",
                            Alpha3Code = "GUM",
                            CountryName = "Guam",
                            InternetDomain = ".gu",
                            NumericCode = 316,
                            SubDivisionCode = "GQ"
                        },
                        new
                        {
                            Id = 2,
                            Alpha2Code = "GN",
                            Alpha3Code = "GIN",
                            CountryName = "Guinea",
                            InternetDomain = ".gn",
                            NumericCode = 324,
                            SubDivisionCode = "GV"
                        },
                        new
                        {
                            Id = 3,
                            Alpha2Code = "LU",
                            Alpha3Code = "LUX",
                            CountryName = "Luxembourg",
                            InternetDomain = ".lu",
                            NumericCode = 442,
                            SubDivisionCode = "LU"
                        },
                        new
                        {
                            Id = 4,
                            Alpha2Code = "SK",
                            Alpha3Code = "SVK",
                            CountryName = "Slovakia",
                            InternetDomain = ".sk",
                            NumericCode = 703,
                            SubDivisionCode = "LO"
                        },
                        new
                        {
                            Id = 5,
                            Alpha2Code = "TF",
                            Alpha3Code = "ATF",
                            CountryName = "French Southern Territories",
                            InternetDomain = ".tf",
                            NumericCode = 260,
                            SubDivisionCode = "FS"
                        },
                        new
                        {
                            Id = 6,
                            Alpha2Code = "BQ",
                            Alpha3Code = "BES",
                            CountryName = "Bonaire, Saint Eustatius and Saba",
                            InternetDomain = ".bq",
                            NumericCode = 535,
                            SubDivisionCode = ""
                        },
                        new
                        {
                            Id = 7,
                            Alpha2Code = "AQ",
                            Alpha3Code = "ATA",
                            CountryName = "Antarctica",
                            InternetDomain = ".aq",
                            NumericCode = 10,
                            SubDivisionCode = "AY"
                        },
                        new
                        {
                            Id = 8,
                            Alpha2Code = "ZA",
                            Alpha3Code = "ZAF",
                            CountryName = "South Africa",
                            InternetDomain = ".za",
                            NumericCode = 710,
                            SubDivisionCode = "SF"
                        },
                        new
                        {
                            Id = 9,
                            Alpha2Code = "SG",
                            Alpha3Code = "SGP",
                            CountryName = "Singapore",
                            InternetDomain = ".sg",
                            NumericCode = 702,
                            SubDivisionCode = "SN"
                        },
                        new
                        {
                            Id = 10,
                            Alpha2Code = "MF",
                            Alpha3Code = "MAF",
                            CountryName = "Saint Martin",
                            InternetDomain = ".gp",
                            NumericCode = 663,
                            SubDivisionCode = "RN"
                        },
                        new
                        {
                            Id = 11,
                            Alpha2Code = "LT",
                            Alpha3Code = "LTU",
                            CountryName = "Lithuania",
                            InternetDomain = ".lt",
                            NumericCode = 440,
                            SubDivisionCode = "LH"
                        },
                        new
                        {
                            Id = 12,
                            Alpha2Code = "IN",
                            Alpha3Code = "IND",
                            CountryName = "India",
                            InternetDomain = ".in",
                            NumericCode = 356,
                            SubDivisionCode = "IN"
                        },
                        new
                        {
                            Id = 13,
                            Alpha2Code = "US",
                            Alpha3Code = "USA",
                            CountryName = "United States",
                            InternetDomain = ".us",
                            NumericCode = 840,
                            SubDivisionCode = "US"
                        },
                        new
                        {
                            Id = 14,
                            Alpha2Code = "PW",
                            Alpha3Code = "PLW",
                            CountryName = "Palau",
                            InternetDomain = ".pw",
                            NumericCode = 585,
                            SubDivisionCode = "PS"
                        },
                        new
                        {
                            Id = 15,
                            Alpha2Code = "KP",
                            Alpha3Code = "PRK",
                            CountryName = "North Korea",
                            InternetDomain = ".kp",
                            NumericCode = 408,
                            SubDivisionCode = "KN"
                        },
                        new
                        {
                            Id = 16,
                            Alpha2Code = "AT",
                            Alpha3Code = "AUT",
                            CountryName = "Austria",
                            InternetDomain = ".at",
                            NumericCode = 40,
                            SubDivisionCode = "AU"
                        },
                        new
                        {
                            Id = 17,
                            Alpha2Code = "MO",
                            Alpha3Code = "MAC",
                            CountryName = "Macao",
                            InternetDomain = ".mo",
                            NumericCode = 446,
                            SubDivisionCode = "MC"
                        },
                        new
                        {
                            Id = 18,
                            Alpha2Code = "MU",
                            Alpha3Code = "MUS",
                            CountryName = "Mauritius",
                            InternetDomain = ".mu",
                            NumericCode = 480,
                            SubDivisionCode = "MP"
                        },
                        new
                        {
                            Id = 19,
                            Alpha2Code = "ST",
                            Alpha3Code = "STP",
                            CountryName = "Sao Tome and Principe",
                            InternetDomain = ".st",
                            NumericCode = 678,
                            SubDivisionCode = "TP"
                        },
                        new
                        {
                            Id = 20,
                            Alpha2Code = "SE",
                            Alpha3Code = "SWE",
                            CountryName = "Sweden",
                            InternetDomain = ".se",
                            NumericCode = 752,
                            SubDivisionCode = "SW"
                        },
                        new
                        {
                            Id = 21,
                            Alpha2Code = "FM",
                            Alpha3Code = "FSM",
                            CountryName = "Micronesia",
                            InternetDomain = ".fm",
                            NumericCode = 583,
                            SubDivisionCode = "FM"
                        },
                        new
                        {
                            Id = 22,
                            Alpha2Code = "HK",
                            Alpha3Code = "HKG",
                            CountryName = "Hong Kong",
                            InternetDomain = ".hk",
                            NumericCode = 344,
                            SubDivisionCode = "HK"
                        },
                        new
                        {
                            Id = 23,
                            Alpha2Code = "IR",
                            Alpha3Code = "IRN",
                            CountryName = "Iran",
                            InternetDomain = ".ir",
                            NumericCode = 364,
                            SubDivisionCode = "IR"
                        },
                        new
                        {
                            Id = 24,
                            Alpha2Code = "GB",
                            Alpha3Code = "GBR",
                            CountryName = "United Kingdom",
                            InternetDomain = ".uk",
                            NumericCode = 826,
                            SubDivisionCode = "UK"
                        },
                        new
                        {
                            Id = 25,
                            Alpha2Code = "DE",
                            Alpha3Code = "DEU",
                            CountryName = "Germany",
                            InternetDomain = ".de",
                            NumericCode = 276,
                            SubDivisionCode = "GM"
                        },
                        new
                        {
                            Id = 26,
                            Alpha2Code = "SK",
                            Alpha3Code = "SVK",
                            CountryName = "Slovakia",
                            InternetDomain = ".sk",
                            NumericCode = 703,
                            SubDivisionCode = "LO"
                        },
                        new
                        {
                            Id = 27,
                            Alpha2Code = "SE",
                            Alpha3Code = "SWE",
                            CountryName = "Sweden",
                            InternetDomain = ".se",
                            NumericCode = 752,
                            SubDivisionCode = "SW"
                        },
                        new
                        {
                            Id = 28,
                            Alpha2Code = "NI",
                            Alpha3Code = "NIC",
                            CountryName = "Nicaragua",
                            InternetDomain = ".ni",
                            NumericCode = 558,
                            SubDivisionCode = "NU"
                        },
                        new
                        {
                            Id = 29,
                            Alpha2Code = "GM",
                            Alpha3Code = "GMB",
                            CountryName = "Gambia",
                            InternetDomain = ".gm",
                            NumericCode = 270,
                            SubDivisionCode = "GA"
                        },
                        new
                        {
                            Id = 30,
                            Alpha2Code = "CR",
                            Alpha3Code = "CRI",
                            CountryName = "Costa Rica",
                            InternetDomain = ".cr",
                            NumericCode = 188,
                            SubDivisionCode = "CS"
                        },
                        new
                        {
                            Id = 31,
                            Alpha2Code = "AU",
                            Alpha3Code = "AUS",
                            CountryName = "Australia",
                            InternetDomain = ".au",
                            NumericCode = 36,
                            SubDivisionCode = "AS"
                        },
                        new
                        {
                            Id = 32,
                            Alpha2Code = "NL",
                            Alpha3Code = "NLD",
                            CountryName = "Netherlands",
                            InternetDomain = ".nl",
                            NumericCode = 528,
                            SubDivisionCode = "NL"
                        },
                        new
                        {
                            Id = 33,
                            Alpha2Code = "MZ",
                            Alpha3Code = "MOZ",
                            CountryName = "Mozambique",
                            InternetDomain = ".mz",
                            NumericCode = 508,
                            SubDivisionCode = "MZ"
                        },
                        new
                        {
                            Id = 34,
                            Alpha2Code = "GU",
                            Alpha3Code = "GUM",
                            CountryName = "Guam",
                            InternetDomain = ".gu",
                            NumericCode = 316,
                            SubDivisionCode = "GQ"
                        },
                        new
                        {
                            Id = 35,
                            Alpha2Code = "GA",
                            Alpha3Code = "GAB",
                            CountryName = "Gabon",
                            InternetDomain = ".ga",
                            NumericCode = 266,
                            SubDivisionCode = "GB"
                        },
                        new
                        {
                            Id = 36,
                            Alpha2Code = "SG",
                            Alpha3Code = "SGP",
                            CountryName = "Singapore",
                            InternetDomain = ".sg",
                            NumericCode = 702,
                            SubDivisionCode = "SN"
                        },
                        new
                        {
                            Id = 37,
                            Alpha2Code = "KG",
                            Alpha3Code = "KGZ",
                            CountryName = "Kyrgyzstan",
                            InternetDomain = ".kg",
                            NumericCode = 417,
                            SubDivisionCode = "KG"
                        },
                        new
                        {
                            Id = 38,
                            Alpha2Code = "MC",
                            Alpha3Code = "MCO",
                            CountryName = "Monaco",
                            InternetDomain = ".mc",
                            NumericCode = 492,
                            SubDivisionCode = "MN"
                        },
                        new
                        {
                            Id = 39,
                            Alpha2Code = "AW",
                            Alpha3Code = "ABW",
                            CountryName = "Aruba",
                            InternetDomain = ".aw",
                            NumericCode = 533,
                            SubDivisionCode = "AA"
                        },
                        new
                        {
                            Id = 40,
                            Alpha2Code = "CC",
                            Alpha3Code = "CCK",
                            CountryName = "Cocos Islands",
                            InternetDomain = ".cc",
                            NumericCode = 166,
                            SubDivisionCode = "CK"
                        },
                        new
                        {
                            Id = 41,
                            Alpha2Code = "SM",
                            Alpha3Code = "SMR",
                            CountryName = "San Marino",
                            InternetDomain = ".sm",
                            NumericCode = 674,
                            SubDivisionCode = "SM"
                        },
                        new
                        {
                            Id = 42,
                            Alpha2Code = "MV",
                            Alpha3Code = "MDV",
                            CountryName = "Maldives",
                            InternetDomain = ".mv",
                            NumericCode = 462,
                            SubDivisionCode = "MV"
                        },
                        new
                        {
                            Id = 43,
                            Alpha2Code = "HN",
                            Alpha3Code = "HND",
                            CountryName = "Honduras",
                            InternetDomain = ".hn",
                            NumericCode = 340,
                            SubDivisionCode = "HO"
                        },
                        new
                        {
                            Id = 44,
                            Alpha2Code = "BS",
                            Alpha3Code = "BHS",
                            CountryName = "Bahamas",
                            InternetDomain = ".bs",
                            NumericCode = 44,
                            SubDivisionCode = "BF"
                        },
                        new
                        {
                            Id = 45,
                            Alpha2Code = "GB",
                            Alpha3Code = "GBR",
                            CountryName = "United Kingdom",
                            InternetDomain = ".uk",
                            NumericCode = 826,
                            SubDivisionCode = "UK"
                        },
                        new
                        {
                            Id = 46,
                            Alpha2Code = "CU",
                            Alpha3Code = "CUB",
                            CountryName = "Cuba",
                            InternetDomain = ".cu",
                            NumericCode = 192,
                            SubDivisionCode = "CU"
                        },
                        new
                        {
                            Id = 47,
                            Alpha2Code = "FM",
                            Alpha3Code = "FSM",
                            CountryName = "Micronesia",
                            InternetDomain = ".fm",
                            NumericCode = 583,
                            SubDivisionCode = "FM"
                        },
                        new
                        {
                            Id = 48,
                            Alpha2Code = "CX",
                            Alpha3Code = "CXR",
                            CountryName = "Christmas Island",
                            InternetDomain = ".cx",
                            NumericCode = 162,
                            SubDivisionCode = "KT"
                        },
                        new
                        {
                            Id = 49,
                            Alpha2Code = "LU",
                            Alpha3Code = "LUX",
                            CountryName = "Luxembourg",
                            InternetDomain = ".lu",
                            NumericCode = 442,
                            SubDivisionCode = "LU"
                        },
                        new
                        {
                            Id = 50,
                            Alpha2Code = "DJ",
                            Alpha3Code = "DJI",
                            CountryName = "Djibouti",
                            InternetDomain = ".dj",
                            NumericCode = 262,
                            SubDivisionCode = "DJ"
                        },
                        new
                        {
                            Id = 51,
                            Alpha2Code = "GA",
                            Alpha3Code = "GAB",
                            CountryName = "Gabon",
                            InternetDomain = ".ga",
                            NumericCode = 266,
                            SubDivisionCode = "GB"
                        },
                        new
                        {
                            Id = 52,
                            Alpha2Code = "PT",
                            Alpha3Code = "PRT",
                            CountryName = "Portugal",
                            InternetDomain = ".pt",
                            NumericCode = 620,
                            SubDivisionCode = "PO"
                        },
                        new
                        {
                            Id = 53,
                            Alpha2Code = "TG",
                            Alpha3Code = "TGO",
                            CountryName = "Togo",
                            InternetDomain = ".tg",
                            NumericCode = 768,
                            SubDivisionCode = "TO"
                        },
                        new
                        {
                            Id = 54,
                            Alpha2Code = "SE",
                            Alpha3Code = "SWE",
                            CountryName = "Sweden",
                            InternetDomain = ".se",
                            NumericCode = 752,
                            SubDivisionCode = "SW"
                        },
                        new
                        {
                            Id = 55,
                            Alpha2Code = "PE",
                            Alpha3Code = "PER",
                            CountryName = "Peru",
                            InternetDomain = ".pe",
                            NumericCode = 604,
                            SubDivisionCode = "PE"
                        },
                        new
                        {
                            Id = 56,
                            Alpha2Code = "LS",
                            Alpha3Code = "LSO",
                            CountryName = "Lesotho",
                            InternetDomain = ".ls",
                            NumericCode = 426,
                            SubDivisionCode = "LT"
                        },
                        new
                        {
                            Id = 57,
                            Alpha2Code = "RS",
                            Alpha3Code = "SRB",
                            CountryName = "Serbia",
                            InternetDomain = ".rs",
                            NumericCode = 688,
                            SubDivisionCode = "RI"
                        },
                        new
                        {
                            Id = 58,
                            Alpha2Code = "AX",
                            Alpha3Code = "ALA",
                            CountryName = "Aland Islands",
                            InternetDomain = ".ax",
                            NumericCode = 248,
                            SubDivisionCode = ""
                        },
                        new
                        {
                            Id = 59,
                            Alpha2Code = "CF",
                            Alpha3Code = "CAF",
                            CountryName = "Central African Republic",
                            InternetDomain = ".cf",
                            NumericCode = 140,
                            SubDivisionCode = "CT"
                        },
                        new
                        {
                            Id = 60,
                            Alpha2Code = "ZM",
                            Alpha3Code = "ZMB",
                            CountryName = "Zambia",
                            InternetDomain = ".zm",
                            NumericCode = 894,
                            SubDivisionCode = "ZA"
                        },
                        new
                        {
                            Id = 61,
                            Alpha2Code = "FK",
                            Alpha3Code = "FLK",
                            CountryName = "Falkland Islands",
                            InternetDomain = ".fk",
                            NumericCode = 238,
                            SubDivisionCode = "FK"
                        },
                        new
                        {
                            Id = 62,
                            Alpha2Code = "DM",
                            Alpha3Code = "DMA",
                            CountryName = "Dominica",
                            InternetDomain = ".dm",
                            NumericCode = 212,
                            SubDivisionCode = "DO"
                        },
                        new
                        {
                            Id = 63,
                            Alpha2Code = "FR",
                            Alpha3Code = "FRA",
                            CountryName = "France",
                            InternetDomain = ".fr",
                            NumericCode = 250,
                            SubDivisionCode = "FR"
                        },
                        new
                        {
                            Id = 64,
                            Alpha2Code = "BG",
                            Alpha3Code = "BGR",
                            CountryName = "Bulgaria",
                            InternetDomain = ".bg",
                            NumericCode = 100,
                            SubDivisionCode = "BU"
                        },
                        new
                        {
                            Id = 65,
                            Alpha2Code = "AR",
                            Alpha3Code = "ARG",
                            CountryName = "Argentina",
                            InternetDomain = ".ar",
                            NumericCode = 32,
                            SubDivisionCode = "AR"
                        },
                        new
                        {
                            Id = 66,
                            Alpha2Code = "PS",
                            Alpha3Code = "PSE",
                            CountryName = "Palestinian Territory",
                            InternetDomain = ".ps",
                            NumericCode = 275,
                            SubDivisionCode = "WE"
                        },
                        new
                        {
                            Id = 67,
                            Alpha2Code = "SR",
                            Alpha3Code = "SUR",
                            CountryName = "Suriname",
                            InternetDomain = ".sr",
                            NumericCode = 740,
                            SubDivisionCode = "NS"
                        },
                        new
                        {
                            Id = 68,
                            Alpha2Code = "LK",
                            Alpha3Code = "LKA",
                            CountryName = "Sri Lanka",
                            InternetDomain = ".lk",
                            NumericCode = 144,
                            SubDivisionCode = "CE"
                        },
                        new
                        {
                            Id = 69,
                            Alpha2Code = "VG",
                            Alpha3Code = "VGB",
                            CountryName = "British Virgin Islands",
                            InternetDomain = ".vg",
                            NumericCode = 92,
                            SubDivisionCode = "VI"
                        },
                        new
                        {
                            Id = 70,
                            Alpha2Code = "BB",
                            Alpha3Code = "BRB",
                            CountryName = "Barbados",
                            InternetDomain = ".bb",
                            NumericCode = 52,
                            SubDivisionCode = "BB"
                        },
                        new
                        {
                            Id = 71,
                            Alpha2Code = "AD",
                            Alpha3Code = "AND",
                            CountryName = "Andorra",
                            InternetDomain = ".ad",
                            NumericCode = 20,
                            SubDivisionCode = "AN"
                        },
                        new
                        {
                            Id = 72,
                            Alpha2Code = "NE",
                            Alpha3Code = "NER",
                            CountryName = "Niger",
                            InternetDomain = ".ne",
                            NumericCode = 562,
                            SubDivisionCode = "NG"
                        },
                        new
                        {
                            Id = 73,
                            Alpha2Code = "VE",
                            Alpha3Code = "VEN",
                            CountryName = "Venezuela",
                            InternetDomain = ".ve",
                            NumericCode = 862,
                            SubDivisionCode = "VE"
                        },
                        new
                        {
                            Id = 74,
                            Alpha2Code = "BJ",
                            Alpha3Code = "BEN",
                            CountryName = "Benin",
                            InternetDomain = ".bj",
                            NumericCode = 204,
                            SubDivisionCode = "BN"
                        },
                        new
                        {
                            Id = 75,
                            Alpha2Code = "PG",
                            Alpha3Code = "PNG",
                            CountryName = "Papua New Guinea",
                            InternetDomain = ".pg",
                            NumericCode = 598,
                            SubDivisionCode = "PP"
                        },
                        new
                        {
                            Id = 76,
                            Alpha2Code = "SS",
                            Alpha3Code = "SSD",
                            CountryName = "South Sudan",
                            InternetDomain = ".ss",
                            NumericCode = 728,
                            SubDivisionCode = "OD"
                        },
                        new
                        {
                            Id = 77,
                            Alpha2Code = "JM",
                            Alpha3Code = "JAM",
                            CountryName = "Jamaica",
                            InternetDomain = ".jm",
                            NumericCode = 388,
                            SubDivisionCode = "JM"
                        },
                        new
                        {
                            Id = 78,
                            Alpha2Code = "ID",
                            Alpha3Code = "IDN",
                            CountryName = "Indonesia",
                            InternetDomain = ".id",
                            NumericCode = 360,
                            SubDivisionCode = "ID"
                        },
                        new
                        {
                            Id = 79,
                            Alpha2Code = "AO",
                            Alpha3Code = "AGO",
                            CountryName = "Angola",
                            InternetDomain = ".ao",
                            NumericCode = 24,
                            SubDivisionCode = "AO"
                        },
                        new
                        {
                            Id = 80,
                            Alpha2Code = "UZ",
                            Alpha3Code = "UZB",
                            CountryName = "Uzbekistan",
                            InternetDomain = ".uz",
                            NumericCode = 860,
                            SubDivisionCode = "UZ"
                        },
                        new
                        {
                            Id = 81,
                            Alpha2Code = "DM",
                            Alpha3Code = "DMA",
                            CountryName = "Dominica",
                            InternetDomain = ".dm",
                            NumericCode = 212,
                            SubDivisionCode = "DO"
                        },
                        new
                        {
                            Id = 82,
                            Alpha2Code = "AE",
                            Alpha3Code = "ARE",
                            CountryName = "United Arab Emirates",
                            InternetDomain = ".ae",
                            NumericCode = 784,
                            SubDivisionCode = "AE"
                        },
                        new
                        {
                            Id = 83,
                            Alpha2Code = "BM",
                            Alpha3Code = "BMU",
                            CountryName = "Bermuda",
                            InternetDomain = ".bm",
                            NumericCode = 60,
                            SubDivisionCode = "BD"
                        },
                        new
                        {
                            Id = 84,
                            Alpha2Code = "ZA",
                            Alpha3Code = "ZAF",
                            CountryName = "South Africa",
                            InternetDomain = ".za",
                            NumericCode = 710,
                            SubDivisionCode = "SF"
                        },
                        new
                        {
                            Id = 85,
                            Alpha2Code = "SG",
                            Alpha3Code = "SGP",
                            CountryName = "Singapore",
                            InternetDomain = ".sg",
                            NumericCode = 702,
                            SubDivisionCode = "SN"
                        },
                        new
                        {
                            Id = 86,
                            Alpha2Code = "LS",
                            Alpha3Code = "LSO",
                            CountryName = "Lesotho",
                            InternetDomain = ".ls",
                            NumericCode = 426,
                            SubDivisionCode = "LT"
                        },
                        new
                        {
                            Id = 87,
                            Alpha2Code = "VE",
                            Alpha3Code = "VEN",
                            CountryName = "Venezuela",
                            InternetDomain = ".ve",
                            NumericCode = 862,
                            SubDivisionCode = "VE"
                        },
                        new
                        {
                            Id = 88,
                            Alpha2Code = "CZ",
                            Alpha3Code = "CZE",
                            CountryName = "Czechia",
                            InternetDomain = ".cz",
                            NumericCode = 203,
                            SubDivisionCode = "EZ"
                        },
                        new
                        {
                            Id = 89,
                            Alpha2Code = "PE",
                            Alpha3Code = "PER",
                            CountryName = "Peru",
                            InternetDomain = ".pe",
                            NumericCode = 604,
                            SubDivisionCode = "PE"
                        },
                        new
                        {
                            Id = 90,
                            Alpha2Code = "CL",
                            Alpha3Code = "CHL",
                            CountryName = "Chile",
                            InternetDomain = ".cl",
                            NumericCode = 152,
                            SubDivisionCode = "CI"
                        },
                        new
                        {
                            Id = 91,
                            Alpha2Code = "NO",
                            Alpha3Code = "NOR",
                            CountryName = "Norway",
                            InternetDomain = ".no",
                            NumericCode = 578,
                            SubDivisionCode = "NO"
                        },
                        new
                        {
                            Id = 92,
                            Alpha2Code = "TL",
                            Alpha3Code = "TLS",
                            CountryName = "Timor Leste",
                            InternetDomain = ".tl",
                            NumericCode = 626,
                            SubDivisionCode = "TT"
                        },
                        new
                        {
                            Id = 93,
                            Alpha2Code = "NF",
                            Alpha3Code = "NFK",
                            CountryName = "Norfolk Island",
                            InternetDomain = ".nf",
                            NumericCode = 574,
                            SubDivisionCode = "NF"
                        },
                        new
                        {
                            Id = 94,
                            Alpha2Code = "SD",
                            Alpha3Code = "SDN",
                            CountryName = "Sudan",
                            InternetDomain = ".sd",
                            NumericCode = 729,
                            SubDivisionCode = "SU"
                        },
                        new
                        {
                            Id = 95,
                            Alpha2Code = "TT",
                            Alpha3Code = "TTO",
                            CountryName = "Trinidad and Tobago",
                            InternetDomain = ".tt",
                            NumericCode = 780,
                            SubDivisionCode = "TD"
                        },
                        new
                        {
                            Id = 96,
                            Alpha2Code = "FI",
                            Alpha3Code = "FIN",
                            CountryName = "Finland",
                            InternetDomain = ".fi",
                            NumericCode = 246,
                            SubDivisionCode = "FI"
                        },
                        new
                        {
                            Id = 97,
                            Alpha2Code = "GQ",
                            Alpha3Code = "GNQ",
                            CountryName = "Equatorial Guinea",
                            InternetDomain = ".gq",
                            NumericCode = 226,
                            SubDivisionCode = "EK"
                        },
                        new
                        {
                            Id = 98,
                            Alpha2Code = "SS",
                            Alpha3Code = "SSD",
                            CountryName = "South Sudan",
                            InternetDomain = ".ss",
                            NumericCode = 728,
                            SubDivisionCode = "OD"
                        },
                        new
                        {
                            Id = 99,
                            Alpha2Code = "GG",
                            Alpha3Code = "GGY",
                            CountryName = "Guernsey",
                            InternetDomain = ".gg",
                            NumericCode = 831,
                            SubDivisionCode = "GK"
                        },
                        new
                        {
                            Id = 100,
                            Alpha2Code = "HM",
                            Alpha3Code = "HMD",
                            CountryName = "Heard Island and McDonald Islands",
                            InternetDomain = ".hm",
                            NumericCode = 334,
                            SubDivisionCode = "HM"
                        });
                });

            modelBuilder.Entity("ENSPRONET.Domains.Domains.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemperatureF")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("WeatherForecast");
                });

            modelBuilder.Entity("ENSPRONET.Domains.Domains.WeatherForecast", b =>
                {
                    b.HasOne("ENSPRONET.Domains.Domains.Country", null)
                        .WithMany("WeatherForecasts")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("ENSPRONET.Domains.Domains.Country", b =>
                {
                    b.Navigation("WeatherForecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
